### ISSUE TITLE
fix import of checkstyle config file containing multiple instances/definitions of the same rules

### ISSUE THREAD

**Issue by ganncamp** [SonarQubeCommunity/sonar-checkstyle#28]
Error when creating a new quality profile by importing a checkstyle configuration:
```
NativeException (javax.persistence.NonUniqueResultException: result returns more than one elements):
    org/hibernate/ejb/QueryImpl.java:109:in `getSingleResult'
    org/sonar/jpa/session/JpaDatabaseSession.java:154:in `getSingleResult'
    org/sonar/core/components/DefaultRuleFinder.java:60:in `find'
    org/sonar/plugins/checkstyle/CheckstyleProfileImporter.java:124:in `processRule'
    org/sonar/plugins/checkstyle/CheckstyleProfileImporter.java:97:in `processModule'
    org/sonar/plugins/checkstyle/CheckstyleProfileImporter.java:69:in `importProfile'
    org/sonar/server/rules/ProfilesConsole.java:140:in `importProfile'
    org/sonar/server/ui/JRubyFacade.java:185:in `importProfile'
    /app/controllers/profiles_controller.rb:71:in `create'
    /app/controllers/profiles_controller.rb:69:in `each_pair'
    /app/controllers/profiles_controller.rb:69:in `create'
    /gems/gems/actionpack-2.2.2/lib/action_controller/base.rb:1253:in `perform_action'
[...]
```
Maybe the issue comes from a rule with cardinality set to multiple... but not sure.

File:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
    This configuration file was written by the eclipse-cs plugin configuration editor
-->
<!--
    Checkstyle-Configuration:
    Description: none
-->
<!DOCTYPE module PUBLIC "-//Puppy Crawl//DTD Check Configuration 1.2//EN" "http://www.puppycrawl.com/dtds/configuration_1_2.dtd">
<module name="Checker">
    <property name="severity" value="warning"/>
    <module name="TreeWalker">
        <property name="tabWidth" value="4"/>
        <module name="AvoidStarImport">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Vérifier qu'il n'y a pas d'imports qui utilisent la notation *"/>
        </module>
        <module name="RedundantImport">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Vérifier qu'il n'y a pas d'imports redondants."/>
            <property name="severity" value="error"/>
        </module>
        <module name="UnusedImports">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Vérifier qu'il n'y a pas d'imports inutilisés"/>
        </module>
        <module name="ImportOrder">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Vérifier le regroupement et l'ordre des imports"/>
            <property name="groups" value="java,javax,org,com,net,sun"/>
        </module>
        <module name="FileLength">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Vérifier la longueur des fichiers sources &gt; 2000"/>
        </module>
        <module name="MethodLength">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Vérifier la longueur des méthodes et/ou constructeurs &gt; 300"/>
            <property name="severity" value="error"/>
            <property name="max" value="300"/>
        </module>
        <module name="ParameterNumber">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Vérifier le nombre de paramètres d'une méthode ou d'un constructeur &gt; 7"/>
        </module>
        <module name="LineLength">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Vérifier la longueur des lignes. &gt; 140"/>
            <property name="ignorePattern" value=".*@see.*"/>
            <property name="max" value="140"/>
            <property name="tabWidth" value="4"/>
        </module>
        <module name="MethodLength">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Vérifier la longueur des méthodes et/ou constructeurs &gt; 200"/>
            <property name="max" value="200"/>
        </module>
        <module name="EmptyForIteratorPad">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Vérifier la partie &quot;itérateur&quot; d'une boucle for lorsqu'elle est vide"/>
            <property name="option" value="space"/>
        </module>
        <module name="MethodParamPad">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Vérifier que l'espacement entre l'identifiant d'une méthode, d'un constructeur, un appel de méthode, l'invocation d'un constructeur; et la parenthèse gauche de la liste des paramètres est respecté"/>
        </module>
        <module name="ParenPad">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Vérifier l'agencement des parenthèses"/>
            <metadata name="com.atlassw.tools.eclipse.checkstyle.lastEnabledSeverity" value="info"/>
            <property name="severity" value="info"/>
        </module>
        <module name="TypecastParenPad">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Vérifier l'agencement des parenthèses lors des trastypages (cast)"/>
            <property name="tokens" value="RPAREN,TYPECAST"/>
        </module>
        <module name="TabCharacter">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Vérifier que le code source ne contient pas de caractÃ¨res de tabulation"/>
        </module>
        <module name="ModifierOrder">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Vérifier l'ordre des modificateurs"/>
        </module>
        <module name="RedundantModifier">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Vérifier la non-redondance des modificateurs"/>
        </module>
        <module name="EmptyBlock">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Vérifier qu'il n'existe pas de blocs vides"/>
            <metadata name="com.atlassw.tools.eclipse.checkstyle.lastEnabledSeverity" value="error"/>
            <property name="severity" value="error"/>
            <property name="option" value="text"/>
        </module>
        <module name="AvoidInlineConditionals">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Détecter les conditions &quot;inline&quot; : valeur = (condition) ? valeur1 : valeur2"/>
            <property name="severity" value="error"/>
        </module>
        <module name="DoubleCheckedLocking">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Vérifier que le &quot;Double Check Idiom&quot; n'est pas utilisé"/>
        </module>
        <module name="EqualsHashCode">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Vérifier que les classes redéfinissant equals() redéfinissent aussi hashCode()"/>
            <property name="severity" value="error"/>
        </module>
        <module name="HiddenField">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Vérifier qu'une variable locale ou un paramètre ne masque pas un champ définit dans la classe"/>
            <property name="ignoreConstructorParameter" value="true"/>
            <property name="ignoreSetter" value="true"/>
        </module>
        <module name="InnerAssignment">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Vérifier qu'il n'y a pas d'assignations dans les sous-expressions"/>
            <property name="severity" value="error"/>
        </module>
        <module name="MagicNumber">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Vérifier qu'il n'y a pas de nombres magiques."/>
        </module>
        <module name="MissingSwitchDefault">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Vérifier que l'instruction &quot;switch&quot; possède une clause &quot;default&quot;"/>
            <property name="severity" value="error"/>
        </module>
        <module name="ModifiedControlVariable">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Vérifier que les variables de boucles &quot;for&quot; ne sont pas modifiées à l'intérieur du bloc &quot;for&quot;"/>
            <property name="severity" value="error"/>
        </module>
        <module name="RedundantThrows">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Vérifier qu'il n'y a pas de redondance dans les clauses &quot;throws&quot;"/>
            <property name="allowUnchecked" value="true"/>
            <property name="allowSubclasses" value="true"/>
        </module>
        <module name="SimplifyBooleanExpression">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Vérifier que les expressions booléennes ne sont pas trop complexes"/>
        </module>
        <module name="SimplifyBooleanReturn">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Vérifier les expressions booléennes de retour de fonction"/>
        </module>
        <module name="StringLiteralEquality">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Verifier que les chaînes de caractères ne sont pas comparées avec les opérateurs == ou !="/>
            <property name="severity" value="error"/>
        </module>
        <module name="NestedIfDepth">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Vérifier la profondeur des blocs &quot;if-else&quot; imbriqués"/>
            <property name="severity" value="error"/>
            <property name="max" value="4"/>
        </module>
        <module name="NestedTryDepth">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Vérifier la profondeur des blocs &quot;try-catch&quot; imbriqués"/>
            <property name="severity" value="error"/>
            <property name="max" value="4"/>
        </module>
        <module name="PackageDeclaration">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Vérifier qu'une classe possède bien une déclaration de package"/>
            <metadata name="com.atlassw.tools.eclipse.checkstyle.lastEnabledSeverity" value="error"/>
            <property name="severity" value="error"/>
        </module>
        <module name="DeclarationOrder">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Vérifier l'ordre de déclaration des parties d'une classe ou d'une interface"/>
        </module>
        <module name="ParameterAssignment">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Interdire l'assignation de paramètres"/>
            <property name="severity" value="error"/>
        </module>
        <module name="ExplicitInitialization">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Verifier si une classe ou un membre d'un objet est explicitement initialisé à la valeur par défaut de son type"/>
        </module>
        <module name="DefaultComesLast">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Vérifier que la clause &quot;default&quot; se trouve après tous les &quot;case&quot; dans une instruction &quot;switch&quot; "/>
        </module>
        <module name="FallThrough">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Vérifie dans les instructions &quot;switch&quot; que tous les blocs &quot;case&quot; contiennent l'instruction break, return, throw ou continue ; en tenant compte des commentaires &quot;fall through&quot;."/>
            <metadata name="com.atlassw.tools.eclipse.checkstyle.lastEnabledSeverity" value="error"/>
            <property name="severity" value="error"/>
        </module>
        <module name="MultipleVariableDeclarations">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Vérifier qu'une déclaration de variable est faite en une seule instruction et qu'il n'y a qu'une seule déclaration par ligne"/>
            <property name="severity" value="error"/>
        </module>
        <module name="UnnecessaryParentheses">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Rechercher des parenthèses inutiles"/>
        </module>
        <module name="VisibilityModifier">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Vérifier la visibilité des membres de classe"/>
            <property name="protectedAllowed" value="true"/>
            <property name="publicMemberPattern" value="^serialVersionUID$"/>
        </module>
        <module name="InterfaceIsType">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Vérifier qu'une interface définit un type (avec des méthodes et pas uniquement des constantes)"/>
            <property name="severity" value="info"/>
        </module>
        <module name="HideUtilityClassConstructor">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Vérifier que les classes dites &quot;utilitaires&quot; (qui définissent uniquement des méthodes statiques) n'ont pas de constructeurs &quot;public&quot;."/>
        </module>
        <module name="ThrowsCount">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Restreindre le nombre de &quot;throws&quot; à un nombre défini"/>
            <property name="max" value="3"/>
        </module>
        <module name="UncommentedMain">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Vérifier qu'une classe ne contient pas de méthode &quot;main&quot; non commentée (dans le cas de main() utilisé pour le debug)"/>
        </module>
        <module name="UpperEll">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Vérifier que les constantes de type &quot;long&quot; sont définies avec un &quot;L&quot; majuscule"/>
        </module>
        <module name="ArrayTypeStyle">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Vérifier le style de définitions des tableaux (la définition façon langage C est prohibée)"/>
        </module>
        <module name="Indentation">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Vérifier que l'indentation du code Java est correcte"/>
        </module>
        <module name="JavadocType">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Vérifier les commentaires Javadoc pour les définitions de classes et d'interfaces"/>
            <property name="authorFormat" value="([A-Z0-9]){2,}"/>
        </module>
        <module name="JavadocMethod">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Vérifier la Javadoc des méthodes et constructeurs"/>
            <property name="allowUndeclaredRTE" value="true"/>
            <property name="allowThrowsTagsForSubclasses" value="true"/>
        </module>
        <module name="JavadocVariable">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Vérifier que les variables de classe ou d'instance privees ont des commentaires Javadoc"/>
            <property name="severity" value="info"/>
            <property name="excludeScope" value="public"/>
        </module>
        <module name="JavadocVariable">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Vérifier que les variables de classe ou d'instance publiques ont des commentaires Javadoc"/>
            <property name="scope" value="public"/>
        </module>
        <module name="JavadocStyle">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Vérifier le style de la Javadoc"/>
            <property name="severity" value="info"/>
            <property name="checkEmptyJavadoc" value="true"/>
            <property name="checkFirstSentence" value="false"/>
        </module>
        <module name="TypeName">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Vérifier la convention de nommage des classes et interfaces"/>
        </module>
        <module name="ConstantName">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Vérifier la convention de nomage des constantes"/>
        </module>
        <module name="LocalFinalVariableName">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Vérifier la convention de nommage des variables locales déclarées &quot;final&quot;"/>
        </module>
        <module name="LocalVariableName">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Vérifier la convention de nommage des variables locales"/>
        </module>
        <module name="MemberName">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Vérifier la convention de nommage des variables d'instance"/>
        </module>
        <module name="StaticVariableName">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Vérifier la convention de nommage des variables de classe"/>
        </module>
        <module name="ParameterName">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Vérifier la convention de nommage des paramètres de fonction"/>
        </module>
        <module name="PackageName">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Vérifier la convention de nommage pour les packages (commence par com.xxxxx ou com.filiiales)"/>
            <property name="format" value="^com\.(xxxxx|filiales)(\.[a-z]+)*$"/>
        </module>
        <module name="MethodName">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Vérifier les conventions de nommage des méthodes"/>
            <property name="format" value="^([a-z][a-zA-Z0-9]*)|((get|set|is|has|can)[A-Z][A-Z0-9]*(_[A-Z0-9]+)*)$"/>
        </module>
        <module name="IllegalToken">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Vérifier qu'il n'y a pas de mots clés interdits dans le code source"/>
            <property name="severity" value="error"/>
            <property name="tokens" value="LABELED_STAT"/>
        </module>
        <module name="IllegalCatch">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Vérifier que certains types d'exceptions ne sont pas catchés."/>
        </module>
        <module name="NoWhitespaceAfter">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Vérifier qu'il n'a pas d'espaces aprÃ¨s certains opÃ©rateurs"/>
            <property name="tokens" value="BNOT,DEC,DOT,INC,LNOT"/>
        </module>
        <module name="NoWhitespaceBefore">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Vérifier qu'il n'y a pas d'espaces avant certains opÃ©rateurs"/>
            <property name="allowLineBreaks" value="true"/>
            <property name="tokens" value="SEMI,DOT,POST_DEC,POST_INC"/>
        </module>
        <module name="OperatorWrap">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Vérifier les conditions de rupture de ligne dans des expressions"/>
            <metadata name="com.atlassw.tools.eclipse.checkstyle.lastEnabledSeverity" value="error"/>
            <property name="severity" value="error"/>
        </module>
        <module name="OperatorWrap">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Vérifier les conditions de rupture de ligne dans des expressions pour les opérateurs d'affectation"/>
            <property name="severity" value="error"/>
            <property name="option" value="eol"/>
            <property name="tokens" value="ASSIGN,BAND_ASSIGN,BOR_ASSIGN,BSR_ASSIGN,BXOR_ASSIGN,DIV_ASSIGN,MINUS_ASSIGN,MOD_ASSIGN,PLUS_ASSIGN,SL_ASSIGN,SR_ASSIGN,STAR_ASSIGN"/>
        </module>
        <module name="WhitespaceAfter">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Vérifier qu'il y a un espace après certains opérateurs"/>
        </module>
        <module name="WhitespaceAround">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Vérifier qu'il y a un espace avant et après certains opérateurs ou mots clés"/>
            <property name="tokens" value="ASSIGN,BAND,BAND_ASSIGN,BOR,BOR_ASSIGN,BSR,BSR_ASSIGN,BXOR,BXOR_ASSIGN,COLON,DIV,DIV_ASSIGN,EQUAL,GE,GT,LAND,LCURLY,LE,LITERAL_ASSERT,LITERAL_CATCH,LITERAL_DO,LITERAL_ELSE,LITERAL_FINALLY,LITERAL_FOR,LITERAL_IF,LITERAL_RETURN,LITERAL_SYNCHRONIZED,LITERAL_TRY,LITERAL_WHILE,LOR,LT,MINUS,MINUS_ASSIGN,MOD,MOD_ASSIGN,NOT_EQUAL,PLUS,PLUS_ASSIGN,QUESTION,RCURLY,SL,SLIST,SL_ASSIGN,SR,SR_ASSIGN,STAR,STAR_ASSIGN,LITERAL_ASSERT,TYPE_EXTENSION_AND"/>
        </module>
        <module name="LeftCurly">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Vérifier le placement des accolades ouvrantes &quot;{&quot;"/>
            <property name="severity" value="error"/>
            <property name="maxLineLength" value="140"/>
        </module>
        <module name="RightCurly">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Vérifier le placement des accolades fermantes &quot;}&quot; en ce qui concerne les mots clés &quot;try&quot;, &quot;catch&quot;, &quot;else&quot;"/>
            <property name="severity" value="error"/>
            <property name="option" value="alone"/>
        </module>
        <module name="FileLength">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Vérifier la longueur des fichiers sources &gt; 5000"/>
            <property name="severity" value="error"/>
            <property name="max" value="5000"/>
        </module>
        <module name="AvoidNestedBlocks">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Eviter les blocs inutiles"/>
            <property name="allowInSwitchCase" value="true"/>
        </module>
        <module name="NeedBraces">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Placer des accolades pour déterminer les blocs do, if, else, for et while"/>
            <property name="severity" value="error"/>
        </module>
        <module name="CovariantEquals">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Vérifier qu'une classe qui définit une méthode equals() prenant un autre type de paramètre qu'Object surcharge également la méthode equals(Object obj)"/>
        </module>
        <module name="EmptyStatement">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Vérifier qu'il n'y a pas de ; inopportun"/>
        </module>
        <module name="IllegalInstantiation">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Passer par la factory ou utiliser les constantes plutot qu'instantier un nouvel objet"/>
            <property name="classes" value="java.lang.Boolean,java.lang.String"/>
        </module>
        <module name="IllegalThrows">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Interdire la levée de RuntimeException, Error et Throwable"/>
            <property name="severity" value="error"/>
        </module>
        <module name="MultipleStringLiterals">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Vérifier qu'il n'y a pas de chaines de caractères redondantes"/>
            <property name="allowedDuplicates" value="5"/>
        </module>
        <module name="FinalClass">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Vérifier qy'une classe qui a uniquement des constructeurs privés est finale"/>
        </module>
        <module name="MutableException">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Vérifier que les membres d'une Exception sont déclarés final"/>
        </module>
        <module name="BooleanExpressionComplexity">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Vérifier que la complexité des expressions booléennes n'est pas trop élevée"/>
            <property name="severity" value="info"/>
            <property name="max" value="5"/>
        </module>
        <module name="ClassFanOutComplexity">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Vérifier que la classe ne dépend pas d'un trop grand nombre d'autres classes"/>
        </module>
        <module name="CyclomaticComplexity">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Vérifier que la complexité cyclomatique n'est pas trop élevée"/>
        </module>
        <module name="JavaNCSS">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Vérifier que la métrique NCSS n'est pas trop élevée"/>
        </module>
        <module name="NPathComplexity">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Vérifie que le nombre de chemins d'exécution possibles n'est pas trop élevé."/>
        </module>
        <module name="j2ee.EntityBean">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Vérifier qu'une classe qui implémente javax.ejb.EntityBean est correcte"/>
        </module>
        <module name="j2ee.FinalStatic">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Vérifier que les champs static d'un EJB sont déclarés final"/>
        </module>
        <module name="j2ee.LocalHomeInterface">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Vérifie qu'une interface qui hérite de javax.ejb.EJBLocalHome est correcte"/>
        </module>
        <module name="j2ee.LocalInterface">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Vérifier qu'une interface qui hérite de javax.ejb.EJBLocalObject est correcte"/>
        </module>
        <module name="j2ee.MessageBean">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Vérifier qu'une classe qui implémente javax.ejb.MessageDrivenBean et javax.jms.MessageListener est correcte"/>
        </module>
        <module name="j2ee.RemoteHomeInterface">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Vérifier qu'une interface qui hérite de javax.ejb.EJBHome est correcte"/>
        </module>
        <module name="j2ee.RemoteInterface">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Vérifier qu'une interface qui hérite de javax.ejb.EJBObject est correcte"/>
        </module>
        <module name="j2ee.SessionBean">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Vérifier qu'une classe qui implémente javax.ejb.SessionBean est correcte"/>
        </module>
        <module name="j2ee.ThisParameter">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Vérifier que this n'est pas utilisé en tant que paramètre de méthodes d'un EJB"/>
        </module>
        <module name="j2ee.ThisReturn">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Vérifier que this n'est pas utilisé en tant que valeur de retour d'une méthode d'un EJB"/>
        </module>
        <module name="IllegalType">
            <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Vérifier l'utilisation d'interfaces ou de classes abstraites au lieu de d'implémentations comme type d'attributs, de paramètres ou de retour."/>
            <property name="tokens" value="METHOD_DEF,PARAMETER_DEF,VARIABLE_DEF"/>
        </module>
    </module>
    <module name="PackageHtml">
        <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Vérifier qu'il existe un fichier package.html pour chaque package."/>
        <metadata name="com.atlassw.tools.eclipse.checkstyle.lastEnabledSeverity" value="info"/>
        <property name="severity" value="info"/>
    </module>
    <module name="StrictDuplicateCode">
        <metadata name="com.atlassw.tools.eclipse.checkstyle.comment" value="Vérifie qu'il n'y a pas de copier/coller de code dans un même fichier"/>
    </module>
</module>
```

**Comment by m-g-sonar** [comment]
This repository is now closed.
Please continue this thread on the new repository of the checkstyle plugin: https://github.com/checkstyle/sonar-checkstyle/issues/3
